name: Security Workflow

on:
  workflow_dispatch:
  pull_request:
  push:
    branches:
      - main

jobs:
  sca:
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        requirements:
          [
            requirements/one-requirements.txt,
            requirements/two-requirements.txt,
            requirements/three-requirements.txt,
          ]
    steps:
      - uses: actions/checkout@master

#      - name: Install Python
#        uses: actions/setup-python@v4
#        with:
#          python-version: "3.11"
#      - name: Install Python Dependencies
#        run: |
#          python3 -m pip install -r ${{ matrix.requirements }}

      - name: Check Python version
        run: |
          python --version

      - name: Run Snyk to check for vulnerabilities
        uses: snyk/actions/python@master
        env:
          COMMAND: pip install -r ${{ matrix.requirements }}
          SNYK_TOKEN: ${{ secrets.SNYK_TOKEN }}
        with:
          args: --package-manager=pip --file=${{ matrix.requirements }} --print-deps -d
